[build]
  command = "npm run build" 
  publish = "./public" 
  functions = "./server" 

[build.environment]
  # Dominio del sitio de producción (Frontend)
	GATSBY_URL= 'http://localhost:9000'
	GATSBY_PRODUCTION='3083'
	GATSBY_DESCARTE='3087'
	# Locations de las netlify functions (Backend) 
	# Son los mismos nombres de los archivos que hay en la carpeta /src/service
  
	GATSBY_URL_EMPLEADOS='/.netlify/functions/empleados'
	GATSBY_URL_FUNCIONES='/.netlify/functions/Funciones'
	GATSBY_URL_FIRMA='/.netlify/functions/GuardarImagen'
	GATSBY_URL_PHOTO='/.netlify/functions/GuardarPhoto'
	GATSBY_URL_EDITARFORMULA='/.netlify/functions/EditarFormula'
	GATSBY_URL_EDITARORDENP='/.netlify/functions/EditarOrdenP'
	GATSBY_URL_EDITARSECUENCIA='/.netlify/functions/EditarSecuencia'
	GATSBY_URL_FORMULA='/.netlify/functions/GetFormula'
	GATSBY_URL_FORMULAS='/.netlify/functions/GetFormulas'
	GATSBY_URL_MENUS='/.netlify/functions/GetMenus'
	GATSBY_URL_ORDENESP='/.netlify/functions/GetOrdenesP'
	GATSBY_URL_ORDENP='/.netlify/functions/GetOrdenP'
	GATSBY_URL_SECUENCIA='/.netlify/functions/GetSecuencia'
	GATSBY_URL_SECUENCIAS='/.netlify/functions/GetSecuencias'
	GATSBY_URL_GUARDARORDENP='/.netlify/functions/GuardarOrdenP'
	GATSBY_URL_GUARDARSECUENCIA='/.netlify/functions/GuardarSecuencia'
	GATSBY_URL_GUARDARFORMULA='/.netlify/functions/GuardarFormula'
	GATSBY_URL_LOGIN='/.netlify/functions/Login'
	GATSBY_URL_COMPRABLES='/.netlify/functions/ProductosComprables'
	GATSBY_URL_VENDIBLES='/.netlify/functions/ProductosVendibles'
	GATSBY_URL_AGENCIAS='/.netlify/functions/Agencias'
	GATSBY_URL_ORDENESVENTA='/.netlify/functions/SaleOrders'
	GATSBY_URL_ORDENVENTA='/.netlify/functions/OrdenVenta'
	GATSBY_URL_EQUIPOS='/.netlify/functions/Equipos'
	GATSBY_URL_RESERVACIONES='/.netlify/functions/Bookings'
	GATSBY_URL_ITEMS='/.netlify/functions/Items'
	GATSBY_URL_PURCHASES='/.netlify/functions/PurchaseOrders'
	GATSBY_URL_PURCHASE='/.netlify/functions/PurchaseOrder'
	GATSBY_URL_RECEIVEPURCHASE='/.netlify/functions/ReceivePurchase'
	GATSBY_URL_NEWITEM='/.netlify/functions/CrearItem'
	GATSBY_URL_GUARDARITEM='/.netlify/functions/GuardarItem'
	GATSBY_URL_EDITPURCHASE='/.netlify/functions/PurchaseOrderEdit'
	GATSBY_URL_ITEMSERIE='/.netlify/functions/GetItemserie'
	GATSBY_URL_DELIVER='/.netlify/functions/Deliver'
	GATSBY_URL_ITEMZAURU='/.netlify/functions/GetItemzauru'
	GATSBY_URL_ITEMORDEN='/.netlify/functions/GetItemorden'
	GATSBY_URL_EXISTENCIAS='/.netlify/functions/GetExistencias'
	GATSBY_URL_LOTEZAURU='/.netlify/functions/GetLoteZauru'
	GATSBY_URL_ENTREGA='/.netlify/functions/GetEntrega'
	GATSBY_URL_LOTEAGENCIA='/.netlify/functions/GetLoteAgencia'
	GATSBY_URL_LOTESAGENCIA='/.netlify/functions/GetLotesAgencia'
	GATSBY_URL_GUARDARLOTEAGENCIA='/.netlify/functions/GuardarLoteAgencia'
	GATSBY_URL_BENEFICIARIOS='/.netlify/functions/Beneficiarios'
	GATSBY_URL_GUARDARPEDIDO='/.netlify/functions/GuardarPedido'
	GATSBY_URL_EDITARPEDIDO='/.netlify/functions/EditarPedido'
	GATSBY_URL_PEDIDO='/.netlify/functions/GetPedido'
	GATSBY_URL_PEDIDOS='/.netlify/functions/GetPedidos'

	# Dominio del sitio de las APIs (Backend)
	GATSBY_ZAURU_URL='https://zauru.herokuapp.com'
	GATSBY_URL_API = 'https://dcgse.com/calendario_api/apical'
	GATSBY_URL_APIP = 'https://dcgse.com/calendario_api/apiprod'
	GATSBY_URL_IMAGES = 'https://dcgse.com/calendario_api/uploads'

	# Locations de los enpoints GET de información a mostrar en los pasos de la app
	GATSBY_APIP_INDEX = ''
	GATSBY_APIP_ORDEN = '/orden'
	GATSBY_APIP_GUARDARORDEN = '/guardarorden'
	GATSBY_APIP_EDITARORDEN = '/editarorden'
	GATSBY_APIP_FORMULAS = '/formulas'
	GATSBY_APIP_FORMULA = '/formula'
	GATSBY_APIP_GUARDARFORMULA = '/guardarformula'
	GATSBY_APIP_EDITARFORMULA = '/editarformula'
	GATSBY_APIP_SECUENCIAS = '/secuencias'
	GATSBY_APIP_SECUENCIA = '/secuencia'
	GATSBY_APIP_GUARDARSECUENCIA = '/guardarsecuencia'
	GATSBY_APIP_EDITARSECUENCIA = '/editarsecuencia'
	GATSBY_APIP_GROUPMENU = '/groupmenu'
	GATSBY_APIP_EQUIPOS = '/equipos'
	GATSBY_APIP_GUARDARITEM = '/guardar_item'
	GATSBY_APIP_GETITEMSERIE = '/getitemserie'
	GATSBY_APIP_GETITEMORDEN = '/getitemorden'
	GATSBY_APIP_GUARDARLOTE = '/guardarlote'
	GATSBY_APIP_EDITARLOTE = '/editar_lote'
	GATSBY_APIP_GETLOTE = '/lote'
	GATSBY_APIP_GETLOTES = '/lotes'
	GATSBY_APIP_EXISTENCIAS= '/excel_existencias'
	GATSBY_APIP_LOTEAGENCIA= '/loteagencia'
	GATSBY_APIP_LOTESAGENCIA= '/lotesagencia'
	GATSBY_APIP_GUARDARLOTEAGENCIA= '/guardarloteag'
	GATSBY_APIP_GUARDARPEDIDO= '/guardarpedido'
	GATSBY_APIP_EDITARPEDIDO= '/editarpedido'
	GATSBY_APIP_PEDIDO= '/pedido'
	GATSBY_APIP_PEDIDOS= '/pedidos'

	#API DE ZAURU

	GATSBY_API_EMPLEADOS='/settings/employees/'	
	GATSBY_API_PRODUCTOSVENDIBLES='/pos/sale_orders/new.json'
	GATSBY_API_PRODUCTOSCOMPRABLES='/purchases/purchase_orders/new.json'
	GATSBY_API_AGENCIAS = '/settings/agencies.json'
	GATSBY_API_ORDENESDEVENTA='/sales/orders/datatables.json'
	GATSBY_API_ORDENDEVENTA='/sales/orders/'
	GATSBY_API_RESERVACIONES='/inventories/bookings.json'
	GATSBY_API_ITEMS='/settings/items.json'
	GATSBY_API_COMPRAS='/purchases/purchase_orders/datatables.json'
	GATSBY_API_COMPRA='/purchases/purchase_orders/'
	GATSBY_API_ITEM='/settings/items.json'
  	GATSBY_API_DELIVER='/inventories/bookings/'
	GATSBY_API_ITEMZAURU='/settings/items/'
	GATSBY_API_CREARLOTE = '/inventories/lots.json'
	GATSBY_API_LOTEZAURU = '/inventories/lots/'
	GATSBY_API_ENTREGA = '/inventories/deliveries/'
	GATSBY_API_BENEFICIARIOS='/settings/payees/datatables.json?scope=clients'

	# Email y token de autenticación para utilizar las APIs 
        GATSBY_EMAIL='api@edesa.com'
    	GATSBY_TOKEN='y749fGvk3B6nC8pMUy4j'
		GATSBY_API_KEY='y749fGvk3B6nC8pMUy4j'
		#GATSBY_EMAIL='api@discogua.com.gt'
        #GATSBY_TOKEN='uuvDJ6vscs1ewsxbRVHU'
		#GATSBY_API_KEY='uuvDJ6vscs1ewsxbRVHU'
	# Variable de entorno para ver los botones de debug. 
	GATSBY_MODO='PROD' # PROD / DEBUG 
